[project]
name = "notte-browser"
version = "1.3.5"
description = "The web browser for LLMs agents"
readme = "README.md"
authors = [
    { name = "Notte Team ", email = "hello@notte.cc" }
]
packages = [
  { include = "notte_browser", from = "src" },
]


requires-python = ">=3.11"
dependencies = [
    "notte_core>=1.3.3",
    "patchright==1.50.0",
    "maincontentextractor",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]

[tool.uv.sources]
maincontentextractor = { git = "https://github.com/HawkClaws/main_content_extractor", rev = "7c3ed7f6ed7f6c10223a3357d43ab741663bc812" }
