[project]
name = "notte-sdk"
version = "1.4.1"
description = "The SDK for Notte"
readme = "README.md"
authors = [
    { name = "Notte Team ", email = "hello@notte.cc" }
]
packages = [
  { include = "notte_sdk", from = "src" },
]

requires-python = ">=3.11"
dependencies = [
    "loguru>=0.7.3",
    "pydantic>=2.11.3",
    "requests>=2.32.3",
    "notte-core>=1.3.3",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
