[project]
name = "notte-core"
version = "1.4.4.dev"
description = "The web browser for LLMs agents"
readme = "README.md"
authors = [
    { name = "Notte Team ", email = "hello@notte.cc" }
]
packages = [
  { include = "notte_core", from = "src" },
]

requires-python = ">=3.11"
dependencies = [
    "chevron>=0.14.0",
    "litellm>=1.74.12",
    "llamux>=0.1.9",
    "loguru>=0.7.3",
    "pillow>=11.1.0",
    "posthog>=3.0.1",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.8.1",
    "pyotp>=2.9.0",
    "python-dotenv>=1.0.1",
    "requests>=2.32.3",
    "tldextract>=5.3.0",
    "toml>=0.10.2",
    "nest_asyncio>=1.6.0",
    "opentelemetry-sdk>=1.34.1",
    "scarf-sdk>=0.1.2",
]

[project.optional-dependencies]
server = [
    "litellm>=1.74.12",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
maincontentextractor = { git = "https://github.com/HawkClaws/main_content_extractor", rev = "7c3ed7f6ed7f6c10223a3357d43ab741663bc812" }
